### ISSUE TITLE
Configuration for HA

### ISSUE THREAD

**Issue by chillinorway** [fredriknk/eikgeiger#7]
To include Geiger to HA -> in configuration.yaml, add:

```
sensor:
  - platform: rest
    name: EIK_Geiger
    resource: http:// <IP-Address> /cpm
    json_attributes:
      - "data"
    value_template: "OK"
  - platform: template
    sensors:
      cpm:
        value_template: "{{ state_attr('sensor.EIK_Geiger', 'data')['cpm'] }}"
        unit_of_measurement: "cpm"
      cpm_m:
        value_template: "{{ state_attr('sensor.EIK_Geiger', 'data')['cpm_M'] }}"
        unit_of_measurement: "cpm_avg_m"
      cpm_h:
        value_template: "{{ state_attr('sensor.EIK_Geiger', 'data')['cpm_H'] }}"
        unit_of_measurement: "cpm_avg_h"
      raw_volt:
        value_template: "{{ state_attr('sensor.EIK_Geiger', 'data')['raw_volt'] }}"
        unit_of_measurement: "raw_voltage"
```
